### ISSUE TITLE
Empty list returned when non-empty list is expected in line 773 in active branch

### ISSUE THREAD

**Issue by a-t-0** [a-t-0/Get-Your-Own-Handwritten-Font#16]
Largest example file, last page.

Note in the 4th found qr codes, qr code symbol indexces are listed which are not contained in the list of (found) `qrcodes`. Next an empty list is returned when a non-empty list is expected. Perhaps, the code expects the found qr codes to be in the `qrcodes` list. If yes find out why the found qrcodes are not in the `qrcodes` list. 

```
found_qrcodes_index=[56, 62, 58, 61, 57, 55, 58, 59],with qrcodes=[56, 62, 58, 53, 46, 51, 45, 43, 38, 41, 40, 34, 30, 28, 31, 32]

found_qrcodes_index=[72, 70, 65, 68, 67],with qrcodes=[56, 62, 58, 53, 46, 51, 45, 43, 38, 41, 40, 34, 30, 28, 31, 32]

found_qrcodes_index=[56, 62, 58, 61, 57, 55, 58, 59],with qrcodes=[56, 62, 58, 53, 46, 51, 45, 43, 38, 41, 40, 34, 30, 28, 31, 32]

found_qrcodes_index=[80, 73, 78],with qrcodes=[56, 62, 58, 53, 46, 51, 45, 43, 38, 41, 40, 34, 30, 28, 31, 32]

Traceback (most recent call last):
  File "read14.py", line 978, in <module>
  File "read14.py", line 102, in perform_runs
    self.loop_through_scanned_images(self.all_cnts,self.no_cnts_filter)
  File "read14.py", line 123, in loop_through_scanned_images
    self.perform_sym_extraction_run(img_name,all_cnts,no_cnts_filter)
  File "read14.py", line 149, in perform_sym_extraction_run
    self.read_qr_imgs(img_name)
  File "read14.py", line 389, in read_qr_imgs
    self.do_geometric_inferencing(img_name,qrcodes)
  File "read14.py", line 155, in do_geometric_inferencing
    self.geometric_inference(img_name,merged_qrcodes)
  File "read14.py", line 661, in geometric_inference
    updated_geometry_data = self.update_geometry(geometry_data,row_nr,nearest_row_with_spacing,qrcodes)
  File "read14.py", line 751, in update_geometry
    updated_geometry_data[3],updated_geometry_data[4] = self.get_interpolate_top_and_bottom(original_row,nearest_row,reference_row,qrcodes)
  File "read14.py", line 773, in get_interpolate_top_and_bottom
    top_reference_row = round(mean(list(map(lambda x: x.top,qrcodes_reference_row))),0) # c_pixels
  File "E:\ProgramData\Anaconda3\envs\py36\lib\statistics.py", line 311, in mean
    raise StatisticsError('mean requires at least one data point')
statistics.StatisticsError: mean requires at least one data point

(py36) ```

**Comment by a-t-0** [comment]
The variable `nrOfLinesPerPage` in `symbol_spec.txt` does not actually represent the number of lines per page when the pdf is created. Instead it represents the number of lines in the document. The actual nr of lines is computed by latex based on the geometry of the qr codes.

As a solution one could create an output file that specifies the number of lines in the pages that are created, such that the reading code knows how many lines it should expect in a page (with the exception of the last/a single page if the number of lines in the document is not integer divisible by the number of lines per page).

**Comment by a-t-0** [comment]
### Solution
0. Change the variable `nrOfLinesPerPage` to `nrOfLinesInTemplate` in the template creation latex.
1. Output a txt file with the `numberOfPages` (with qr codes) on the first line, the `nrOfLinesPerPage` on consecutive pages.
2. Next, in the template reading code, the `self.nrOfLinesPerPage` should be determined using a single found qr code on the page (which contains an index number
, which can be used to determine the page number of the qr code based on the outputted number of lines for each page)

**Comment by a-t-0** [comment]
#Closed in pull request 19, which is propagated to main through issue 10 and issue 1.
